theme: jekyll-theme-minimal

title: Kulvinder Singh
description: Senior Backend Engineer | Python, Django, Distributed Systems

author: Kulvinder Singh

markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

url: "https://kulvinder26.github.io"
baseurl: ""

show_downloads: false
google_analytics: ""
